<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MarcasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('marcas')->delete();
        
        \DB::table('marcas')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => '3D',
                'address' => 'Asistencia Pública 708, Col. Federal C.P. 15700, Venustiano Carranza, CDMX.',
                'email' => '3dstorecdmx@gmail.com',
                'web' => NULL,
                'instagram' => '@3d_products_mexico',
                'facebook' => '3D Store CDMX',
                'phone' => NULL,
                'created_at' => '2021-10-21 18:36:09',
                'updated_at' => '2021-10-21 18:36:09',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'JESCAR',
                'address' => 'Dir. Asistencia Pública 708, Col. Federal C.P. 15700, Venustiano Carranza, CDMX.',
                'email' => '3dstorecdmx@gmail.com',
                'web' => NULL,
                'instagram' => '@3d_products_mexico',
                'facebook' => '3D Store CDMX',
                'phone' => NULL,
                'created_at' => '2021-10-21 18:37:46',
                'updated_at' => '2021-10-21 18:37:46',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'TONYIN',
                'address' => 'Asistencia Pública 708, Col. Federal C.P. 15700, Venustiano Carranza, CDMX.',
                'email' => '3dstorecdmx@gmail.com',
                'web' => NULL,
                'instagram' => '@3d_products_mexico',
                'facebook' => '3D Store CDMX',
                'phone' => NULL,
                'created_at' => '2021-10-21 18:39:05',
                'updated_at' => '2021-10-21 18:39:05',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'SM ARNOLD',
                'address' => 'Asistencia Pública 708, Col. Federal C.P. 15700, Venustiano Carranza, CDMX.',
                'email' => '3dstorecdmx@gmail.com',
                'web' => NULL,
                'instagram' => '@3d_products_mexico',
                'facebook' => '3D Store CDMX',
                'phone' => NULL,
                'created_at' => '2021-10-21 18:40:18',
                'updated_at' => '2021-10-21 18:40:18',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'LAKE COUNTRY',
                'address' => 'Asistencia Pública 708, Col. Federal C.P. 15700, Venustiano Carranza, CDMX',
                'email' => '3dstorecdmx@gmail.com',
                'web' => NULL,
                'instagram' => '@3d_products_mexico',
                'facebook' => '3D Store CDMX',
                'phone' => NULL,
                'created_at' => '2021-10-21 18:42:25',
                'updated_at' => '2021-10-21 18:42:25',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'FLEX',
                'address' => 'Asistencia Pública 708, Col. Federal C.P. 15700, Venustiano Carranza, CDMX.',
                'email' => '3dstorecdmx@gmail.com',
                'web' => NULL,
                'instagram' => '@3d_products_mexico',
                'facebook' => ': 3D Store CDMX',
                'phone' => NULL,
                'created_at' => '2021-10-21 18:44:27',
                'updated_at' => '2021-10-21 18:44:27',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'The Lab',
                'address' => 'Plazuela de Los Reyes 27, Los Reyes Coyoacán C.P 04330, CDMX.',
                'email' => 'thelabmexico.studio@gmail.com',
                'web' => 'http://www.thelabmexico.com.mx/',
                'instagram' => '@thelabmexico',
                'facebook' => 'The Lab México',
                'phone' => '55 6890 0194',
                'created_at' => '2021-10-21 18:46:43',
                'updated_at' => '2021-10-21 18:46:43',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Chemical Guys',
                'address' => 'Plazuela de Los Reyes 27, Los Reyes Coyoacán C.P 04330, CDMX.',
                'email' => 'thelabmexico.studio@gmail.com',
                'web' => 'http://www.thelabmexico.com.mx/',
                'instagram' => '@thelabmexico',
                'facebook' => 'The Lab México',
                'phone' => '55 6890 0194',
                'created_at' => '2021-10-21 18:48:09',
                'updated_at' => '2021-10-21 18:48:09',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'FEYNLAB',
                'address' => 'Plazuela de Los Reyes 27, Los Reyes Coyoacán C.P 04330, CDMX',
                'email' => 'thelabmexico.studio@gmail.com',
                'web' => 'http://www.thelabmexico.com.mx/',
                'instagram' => '@thelabmexico',
                'facebook' => 'The Lab México',
                'phone' => '55 6890 0194',
                'created_at' => '2021-10-23 21:52:56',
                'updated_at' => '2021-10-23 23:38:31',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Makita',
                'address' => 'Plazuela de Los Reyes 27, Los Reyes Coyoacán C.P 04330, CDMX',
                'email' => 'thelabmexico.studio@gmail.com',
                'web' => 'http://www.thelabmexico.com.mx/',
                'instagram' => '@thelabmexico',
                'facebook' => 'The Lab México',
                'phone' => '55 6890 0194',
                'created_at' => '2021-10-23 23:35:13',
                'updated_at' => '2021-10-23 23:35:13',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'MIRKA',
                'address' => 'Plazuela de Los Reyes 27, Los Reyes Coyoacán C.P 04330, CDMX',
                'email' => 'thelabmexico.studio@gmail.com',
                'web' => 'http://www.thelabmexico.com.mx/',
                'instagram' => '@thelabmexico',
                'facebook' => 'The Lab México',
                'phone' => '55 6890 0194',
                'created_at' => '2021-10-23 23:38:06',
                'updated_at' => '2021-10-23 23:38:06',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'X-KOTE',
                'address' => 'Plazuela de Los Reyes 27, Los Reyes Coyoacán C.P 04330, CDMX',
                'email' => 'thelabmexico.studio@gmail.com',
                'web' => 'http://www.thelabmexico.com.mx/',
                'instagram' => '@thelabmexico',
                'facebook' => 'The Lab México',
                'phone' => '55 6890 0194',
                'created_at' => '2021-10-23 23:40:26',
                'updated_at' => '2021-10-23 23:40:26',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'LAVOR',
                'address' => 'Plazuela de Los Reyes 27, Los Reyes Coyoacán C.P 04330, CDMX',
                'email' => 'thelabmexico.studio@gmail.com',
                'web' => 'http://www.thelabmexico.com.mx/',
                'instagram' => '@thelabmexico',
                'facebook' => 'The Lab México',
                'phone' => '55 6890 0194',
                'created_at' => '2021-10-23 23:41:42',
                'updated_at' => '2021-10-23 23:41:42',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Service Car Detail',
                'address' => 'Jilotepec 382, Habitacional La Romana, C.P. 54030 TLALNEPANTLA Edo. De Mex',
                'email' => 'servicecardtl@gmail.com',
                'web' => NULL,
                'instagram' => '@servicecar_detail',
                'facebook' => 'Service Car Detail',
                'phone' => '5539846825',
                'created_at' => '2021-10-23 23:42:55',
                'updated_at' => '2021-10-23 23:42:55',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Magno Clean',
                'address' => 'Reina Tzapozintli núm. 433 Col. Pachagüillo , Tonalá Jalisco',
                'email' => 'ventas@magnoclean.com',
                'web' => 'http://www.magnoclean.com/',
                'instagram' => NULL,
                'facebook' => 'Magno Clean de México',
                'phone' => '33 2760 6138',
                'created_at' => '2021-10-23 23:44:11',
                'updated_at' => '2021-10-23 23:44:11',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'VAPORZA',
                'address' => 'Gladiola 65, Col. Agrícola C.P. 45263 Zapopan, Jalisco',
                'email' => 'info@vaporza.com.mx',
                'web' => 'https://vaporza.com.mx/',
                'instagram' => '@vaporseco',
                'facebook' => 'Vaporza',
                'phone' => '3336843628',
                'created_at' => '2021-10-23 23:45:45',
                'updated_at' => '2021-10-23 23:45:45',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'GYEON',
                'address' => 'Vía Adolfo López Mateos 98, Jardines Bellavista C.P 54040, TLALNEPANTLA EDO DE MEX',
                'email' => 'contacto@ppmcarstudio.com',
                'web' => 'http://www.ppmcarstudio.com/',
                'instagram' => '@ppmcarstudiomx',
                'facebook' => 'PPM Car Studio MX',
                'phone' => '55 3005 8829',
                'created_at' => '2021-10-23 23:47:17',
                'updated_at' => '2021-10-23 23:47:17',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'AUTOFINISH',
                'address' => 'Gabrielle D\'annunzio 4773, Lomas Universidad, C.P. 45027 Zapopan, Jal',
                'email' => 'contacto@autofinish.mx',
                'web' => 'https://www.autofinish.mx/',
                'instagram' => '@autofinish_official',
                'facebook' => 'AUTOFINISH',
                'phone' => '33 1814 6044',
                'created_at' => '2021-10-23 23:49:09',
                'updated_at' => '2021-10-23 23:49:09',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'OM BODYSHOP',
                'address' => 'Av. Enríque Díaz de león 37, Atemajac del Valle C.P. 45190, ZAPOPAN JALISCO',
                'email' => 'ombodyshop37@gmail.com',
                'web' => 'http://www.ombodyshop.com/',
                'instagram' => '@ombodyshop',
                'facebook' => 'OM Bodyshop Detallado Profesional',
                'phone' => '33 1107 2703',
                'created_at' => '2021-10-23 23:51:17',
                'updated_at' => '2021-10-23 23:51:17',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Sheik’s Detail',
                'address' => 'Miguel G Kramer 103-interior 3, Atlántida, Coyoacán, C.P. 04370 Ciudad de México, CDMX',
                'email' => 'info@sheiksdetail.com',
                'web' => 'https://www.youtube.com/user/sheik2008',
                'instagram' => '@sheik.detail',
                'facebook' => 'Sheik’s Detail',
                'phone' => '55 3800 4732',
                'created_at' => '2021-10-23 23:53:24',
                'updated_at' => '2021-10-23 23:53:24',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Perfect Shine',
                'address' => 'Avenida 16 de septiembre 5105, C.P. 72534 Puebla de Zaragoza, México',
                'email' => 'perfectshineredes@gmail.com',
                'web' => NULL,
                'instagram' => '@perfectshinemx',
                'facebook' => 'Perfect Shine',
                'phone' => '2227050227',
                'created_at' => '2021-10-23 23:54:58',
                'updated_at' => '2021-10-23 23:54:58',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Detailing Depot',
                'address' => 'Avenida 16 de septiembre 5103, C.P. 72440 Puebla de Zaragoza, México',
                'email' => 'detailingdepotpuebla@gmail.com',
                'web' => NULL,
                'instagram' => '@detailingdepotmx',
                'facebook' => 'Detailing Depot',
                'phone' => '2215210724',
                'created_at' => '2021-10-23 23:56:20',
                'updated_at' => '2021-10-23 23:56:20',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'CALEX',
                'address' => NULL,
                'email' => NULL,
                'web' => 'http://www.calefaccionexterior.mx/',
                'instagram' => NULL,
                'facebook' => 'CALEX',
                'phone' => '55 4130 0506',
                'created_at' => '2021-10-24 00:01:12',
                'updated_at' => '2021-10-24 00:01:12',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Cienfuegos Detallado Automotriz',
                'address' => NULL,
                'email' => 'eumir_cienfuegos82@hotmail.com',
                'web' => NULL,
                'instagram' => '@cienfuegosdetalladoautomotriz',
                'facebook' => 'Cienfuegos detallado automotriz',
                'phone' => '5513855577',
                'created_at' => '2021-10-24 00:02:28',
                'updated_at' => '2021-10-24 00:02:28',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'MARGREY',
                'address' => 'Marte 473 Jardines de Mocambo, Boca del Río Veracruz',
                'email' => NULL,
                'web' => NULL,
                'instagram' => NULL,
                'facebook' => NULL,
                'phone' => '2291742323',
                'created_at' => '2021-10-24 00:03:49',
                'updated_at' => '2021-10-24 00:03:49',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'BRILLAMEX',
                'address' => 'Calle 5 Sur 4920, Residencial Boulevares, C.P 72440, PUEBLA DE ZARAGOZA',
                'email' => 'jmng_83@hotmail.com',
                'web' => NULL,
                'instagram' => '@Brillamexn',
                'facebook' => 'Brillamex Puebla',
                'phone' => '2224645516',
                'created_at' => '2021-10-24 00:05:07',
                'updated_at' => '2021-10-24 00:05:07',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'BANDROP',
                'address' => 'Rinconada de Las Acacias 126, Rinconada del Sol,C.P. 45055 Zapopan, Jal',
                'email' => 'bandropmx@gmail.com',
                'web' => NULL,
                'instagram' => NULL,
                'facebook' => 'Bandrop mx',
                'phone' => '33 3060 4312 y 3311343839',
                'created_at' => '2021-10-24 01:22:01',
                'updated_at' => '2021-10-24 01:22:01',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'SUPREME SHINE PREMIER',
                'address' => 'San Emeterio Mza 636 lote 7, Pedregal de Santa úrsula C.P. 04600. Coyoacán, Ciudad de México',
                'email' => NULL,
                'web' => NULL,
                'instagram' => NULL,
                'facebook' => 'Supreme Shine Premier México',
                'phone' => '5549091550',
                'created_at' => '2021-10-24 01:23:54',
                'updated_at' => '2021-10-24 01:23:54',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'PERFUMES CARBLOCK',
                'address' => NULL,
                'email' => NULL,
                'web' => 'https://carblockmexico.com.mx/',
                'instagram' => '@carblockmexico',
                'facebook' => 'Car Block México',
                'phone' => '55 5953 3360',
                'created_at' => '2021-10-24 01:25:22',
                'updated_at' => '2021-10-24 01:25:22',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'WASH MONKEY',
                'address' => 'A Las Animas, Ixtapalcalco, 54660 Coyotepec, Estado de México',
                'email' => NULL,
                'web' => NULL,
                'instagram' => '@washmonky',
                'facebook' => 'Wash monkey',
                'phone' => '55 1848 8845',
                'created_at' => '2021-10-24 01:26:40',
                'updated_at' => '2021-10-24 01:26:40',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'QDOS',
                'address' => NULL,
                'email' => NULL,
                'web' => NULL,
                'instagram' => NULL,
                'facebook' => 'Rel Qdos',
                'phone' => '5536648621',
                'created_at' => '2021-10-24 01:29:04',
                'updated_at' => '2021-10-24 01:29:04',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'BLACK DRAGON STUDIO',
                'address' => 'C. Oleoducto 1112, Col. Liberación, Azcapotzalco, C.P. 02930 Ciudad de México, CDMX',
                'email' => 'blackdragonstudio.01@gmail.com',
                'web' => NULL,
                'instagram' => NULL,
                'facebook' => 'Black Dragon Studio',
                'phone' => '5537176603',
                'created_at' => '2021-10-24 01:34:51',
                'updated_at' => '2021-10-24 01:34:51',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}