<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_type' => 'App\\Models\\ContactContact',
                'model_id' => 1,
                'uuid' => '2c499638-c2ec-453a-8c04-24da2e096866',
                'collection_name' => 'logo',
                'name' => '61564247b2522_logo-solo',
                'file_name' => '61564247b2522_logo-solo.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 284872,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2021-09-30 23:05:49',
                'updated_at' => '2021-09-30 23:05:52',
            ),
            1 => 
            array (
                'id' => 2,
                'model_type' => 'App\\Models\\ContactCompany',
                'model_id' => 1,
                'uuid' => 'a770844b-3155-4596-af3b-363df9a1ba75',
                'collection_name' => 'company_logo',
                'name' => '6156431309b67_logo-solo',
                'file_name' => '6156431309b67_logo-solo.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 284872,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2021-09-30 23:08:08',
                'updated_at' => '2021-09-30 23:08:09',
            ),
            2 => 
            array (
                'id' => 3,
                'model_type' => 'App\\Models\\HeaderPhoto',
                'model_id' => 1,
                'uuid' => 'd7e12b67-1205-46fc-8499-d24eff68e488',
                'collection_name' => 'upper_photo',
                'name' => '615b344c0db30_4',
                'file_name' => '615b344c0db30_4.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 165930,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2021-10-04 17:05:17',
                'updated_at' => '2021-10-04 17:05:19',
            ),
            3 => 
            array (
                'id' => 4,
                'model_type' => 'App\\Models\\Slider',
                'model_id' => 1,
                'uuid' => '9b5e69c4-957f-4423-9551-9194cd58ae90',
                'collection_name' => 'slider',
                'name' => '6164b1f824fcc_1',
                'file_name' => '6164b1f824fcc_1.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 119930,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 4,
                'created_at' => '2021-10-11 21:56:20',
                'updated_at' => '2021-10-11 21:56:22',
            ),
            4 => 
            array (
                'id' => 5,
                'model_type' => 'App\\Models\\Slider',
                'model_id' => 2,
                'uuid' => '721b6fd9-b6b0-4160-85e3-6b2f54c2dbbe',
                'collection_name' => 'slider',
                'name' => '6164b38833f34_2',
                'file_name' => '6164b38833f34_2.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 117029,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 5,
                'created_at' => '2021-10-11 21:59:23',
                'updated_at' => '2021-10-11 21:59:24',
            ),
            5 => 
            array (
                'id' => 6,
                'model_type' => 'App\\Models\\Slider',
                'model_id' => 3,
                'uuid' => '29724ec8-5cac-448e-b8e5-eb8a95fbfe8b',
                'collection_name' => 'slider',
                'name' => '6164b3ce772e9_3',
                'file_name' => '6164b3ce772e9_3.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 95725,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 6,
                'created_at' => '2021-10-11 22:00:08',
                'updated_at' => '2021-10-11 22:00:09',
            ),
            6 => 
            array (
                'id' => 7,
                'model_type' => 'App\\Models\\Sponsor',
                'model_id' => 1,
                'uuid' => '2ca19d02-603f-4093-92ce-616124afde0d',
                'collection_name' => 'logo',
                'name' => '6164b5b0b487e_schedule',
                'file_name' => '6164b5b0b487e_schedule.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 7031,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 7,
                'created_at' => '2021-10-11 22:07:57',
                'updated_at' => '2021-10-11 22:07:58',
            ),
            7 => 
            array (
                'id' => 11,
                'model_type' => 'App\\Models\\ServicePhoto',
                'model_id' => 1,
                'uuid' => '9bd5ae90-8759-4f32-9a77-9c869768d83d',
                'collection_name' => 'photo',
                'name' => '61678f6f76529_Servicios2',
                'file_name' => '61678f6f76529_Servicios2.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 150373,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 8,
                'created_at' => '2021-10-14 02:01:21',
                'updated_at' => '2021-10-14 02:01:21',
            ),
            8 => 
            array (
                'id' => 12,
                'model_type' => 'App\\Models\\ThruTime',
                'model_id' => 1,
                'uuid' => '297650f3-d04c-497d-bba7-e8b560df4057',
                'collection_name' => 'icon',
                'name' => '616c8d9e63fcc_evento',
                'file_name' => '616c8d9e63fcc_evento.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 9316,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 9,
                'created_at' => '2021-10-17 20:54:57',
                'updated_at' => '2021-10-17 20:54:59',
            ),
            9 => 
            array (
                'id' => 13,
                'model_type' => 'App\\Models\\Testimonial',
                'model_id' => 1,
                'uuid' => '1c8dad63-df88-4e31-a06e-a7c833cf01e3',
                'collection_name' => 'photo',
                'name' => '616c8ddb7221b_GerardoCabrera',
                'file_name' => '616c8ddb7221b_GerardoCabrera.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 55040,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 10,
                'created_at' => '2021-10-17 20:55:56',
                'updated_at' => '2021-10-17 20:55:57',
            ),
            10 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\Testimonial',
                'model_id' => 2,
                'uuid' => 'bed0b4dd-a42b-4909-8b6d-f168d6dc4266',
                'collection_name' => 'photo',
                'name' => '616c8df3a21a9_OctavioMartinez',
                'file_name' => '616c8df3a21a9_OctavioMartinez.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 70096,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 11,
                'created_at' => '2021-10-17 20:56:20',
                'updated_at' => '2021-10-17 20:56:21',
            ),
            11 => 
            array (
                'id' => 16,
                'model_type' => 'App\\Models\\Testimonial',
                'model_id' => 4,
                'uuid' => '65486704-11c2-4e01-b1f8-a08b46f84c58',
                'collection_name' => 'photo',
                'name' => '616c8e194cd9c_FelipeRocha',
                'file_name' => '616c8e194cd9c_FelipeRocha.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 88640,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 13,
                'created_at' => '2021-10-17 20:57:01',
                'updated_at' => '2021-10-17 20:57:02',
            ),
            12 => 
            array (
                'id' => 17,
                'model_type' => 'App\\Models\\Testimonial',
                'model_id' => 5,
                'uuid' => '6da467d5-bf48-40cb-857c-e2f824bcdcdc',
                'collection_name' => 'photo',
                'name' => '616c8e34c74cc_SaúlReyes',
                'file_name' => '616c8e34c74cc_SaúlReyes.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 167819,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 14,
                'created_at' => '2021-10-17 20:57:25',
                'updated_at' => '2021-10-17 20:57:26',
            ),
            13 => 
            array (
                'id' => 18,
                'model_type' => 'App\\Models\\Testimonial',
                'model_id' => 6,
                'uuid' => '8fdb3f42-7cc9-4683-a236-d571d8ba591a',
                'collection_name' => 'photo',
                'name' => '616c8e488909d_AlexanderSalnikov',
                'file_name' => '616c8e488909d_AlexanderSalnikov.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 33265,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 15,
                'created_at' => '2021-10-17 20:57:45',
                'updated_at' => '2021-10-17 20:57:46',
            ),
            14 => 
            array (
                'id' => 19,
                'model_type' => 'App\\Models\\PhotoDescriptionGral',
                'model_id' => 1,
                'uuid' => 'ba534484-77d5-4c5b-a781-b8d295c343de',
                'collection_name' => 'photo',
                'name' => '616c8fbfd34ac_Desdetalladadelevento',
                'file_name' => '616c8fbfd34ac_Desdetalladadelevento.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 221763,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 16,
                'created_at' => '2021-10-17 21:04:17',
                'updated_at' => '2021-10-17 21:04:17',
            ),
            15 => 
            array (
                'id' => 20,
                'model_type' => 'App\\Models\\Testimonial',
                'model_id' => 3,
                'uuid' => 'be0799b0-ed08-4a71-8b02-abd67aa256cc',
                'collection_name' => 'photo',
                'name' => '616c99794055d_MarcoRosas',
                'file_name' => '616c99794055d_MarcoRosas.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 307637,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 17,
                'created_at' => '2021-10-17 21:45:30',
                'updated_at' => '2021-10-17 21:45:30',
            ),
            16 => 
            array (
                'id' => 21,
                'model_type' => 'App\\Models\\ThruTime',
                'model_id' => 2,
                'uuid' => 'f177bdca-cb68-46da-9108-5ee6763ae87d',
                'collection_name' => 'icon',
                'name' => '616c9bd6e285e_evento',
                'file_name' => '616c9bd6e285e_evento.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 9316,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 18,
                'created_at' => '2021-10-17 21:55:35',
                'updated_at' => '2021-10-17 21:55:36',
            ),
            17 => 
            array (
                'id' => 22,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 1,
                'uuid' => '0d06d7c1-6a84-4bdc-8dfb-3eac0b69eb2a',
                'collection_name' => 'logo',
                'name' => '6171b23b4ea2e_3d',
                'file_name' => '6171b23b4ea2e_3d.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 64444,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 19,
                'created_at' => '2021-10-21 18:36:09',
                'updated_at' => '2021-10-21 18:36:10',
            ),
            18 => 
            array (
                'id' => 24,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 2,
                'uuid' => '9b737f64-aa37-4e84-b941-fe535ccb37b7',
                'collection_name' => 'logo',
                'name' => '6171b37232acc_jescar',
                'file_name' => '6171b37232acc_jescar.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 73313,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 21,
                'created_at' => '2021-10-21 18:37:46',
                'updated_at' => '2021-10-21 18:37:47',
            ),
            19 => 
            array (
                'id' => 26,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 3,
                'uuid' => '9ffb407a-595a-4e7b-bb3f-e2c3c9a32db2',
                'collection_name' => 'logo',
                'name' => '6171b3bf46e9d_tonyin',
                'file_name' => '6171b3bf46e9d_tonyin.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 21472,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 23,
                'created_at' => '2021-10-21 18:39:05',
                'updated_at' => '2021-10-21 18:39:05',
            ),
            20 => 
            array (
                'id' => 28,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 4,
                'uuid' => 'ff59d980-e6bf-4527-b23d-4f6d6bceb6f9',
                'collection_name' => 'logo',
                'name' => '6171b41139cbe_smarnold',
                'file_name' => '6171b41139cbe_smarnold.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 146178,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 25,
                'created_at' => '2021-10-21 18:40:18',
                'updated_at' => '2021-10-21 18:40:19',
            ),
            21 => 
            array (
                'id' => 30,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 5,
                'uuid' => 'a70189b7-570b-4577-8405-4f2277bec75a',
                'collection_name' => 'logo',
                'name' => '6171b48041387_lake-country',
                'file_name' => '6171b48041387_lake-country.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 39692,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 27,
                'created_at' => '2021-10-21 18:42:25',
                'updated_at' => '2021-10-21 18:42:26',
            ),
            22 => 
            array (
                'id' => 32,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 6,
                'uuid' => 'c04fc34b-4304-4fb3-a58f-94fe70ac8fa1',
                'collection_name' => 'logo',
                'name' => '6171b5022b525_FLEX',
                'file_name' => '6171b5022b525_FLEX.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 4504,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 29,
                'created_at' => '2021-10-21 18:44:27',
                'updated_at' => '2021-10-21 18:44:28',
            ),
            23 => 
            array (
                'id' => 34,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 7,
                'uuid' => '55316912-0f37-44cd-bbeb-085af4d283d4',
                'collection_name' => 'logo',
                'name' => '6171b586ea87b_the-lab1',
                'file_name' => '6171b586ea87b_the-lab1.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 240285,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 31,
                'created_at' => '2021-10-21 18:46:43',
                'updated_at' => '2021-10-21 18:46:43',
            ),
            24 => 
            array (
                'id' => 36,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 8,
                'uuid' => '81994cff-a45d-4d5a-b011-2ba7b7f8cdc6',
                'collection_name' => 'logo',
                'name' => '6171b5e78317e_chemical-guys',
                'file_name' => '6171b5e78317e_chemical-guys.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 29424,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 33,
                'created_at' => '2021-10-21 18:48:09',
                'updated_at' => '2021-10-21 18:48:09',
            ),
            25 => 
            array (
                'id' => 38,
                'model_type' => 'App\\Models\\ExposerImage',
                'model_id' => 1,
                'uuid' => '42a3eaae-7e74-424c-ab2d-2db5ce7366a7',
                'collection_name' => 'image',
                'name' => '617365cfa5c26_VENTAJAS',
                'file_name' => '617365cfa5c26_VENTAJAS.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 96543,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 35,
                'created_at' => '2021-10-23 01:30:57',
                'updated_at' => '2021-10-23 01:30:58',
            ),
            26 => 
            array (
                'id' => 39,
                'model_type' => 'App\\Models\\ExhibitorImage',
                'model_id' => 1,
                'uuid' => 'd5da36bc-5701-4e29-8db4-abb85565c938',
                'collection_name' => 'photo',
                'name' => '6174493f8d020_VuelveteExpositor',
                'file_name' => '6174493f8d020_VuelveteExpositor.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 251124,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 36,
                'created_at' => '2021-10-23 17:41:27',
                'updated_at' => '2021-10-23 17:41:29',
            ),
            27 => 
            array (
                'id' => 40,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 9,
                'uuid' => 'ba95d5f8-0bf7-46c1-8f89-ebdfb09c80e6',
                'collection_name' => 'logo',
                'name' => '6174843643fa2_feynlab',
                'file_name' => '6174843643fa2_feynlab.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 19360,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 37,
                'created_at' => '2021-10-23 21:52:56',
                'updated_at' => '2021-10-23 21:52:57',
            ),
            28 => 
            array (
                'id' => 44,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 10,
                'uuid' => 'dc5b553a-5a60-4d6a-8666-debee3265fde',
                'collection_name' => 'logo',
                'name' => '61749c7556c84_MAKITA',
                'file_name' => '61749c7556c84_MAKITA.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 25131,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 41,
                'created_at' => '2021-10-23 23:36:23',
                'updated_at' => '2021-10-23 23:36:23',
            ),
            29 => 
            array (
                'id' => 46,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 11,
                'uuid' => '0dca5a59-9266-4338-ad34-62b6aae35a44',
                'collection_name' => 'logo',
                'name' => '61749cdc2a3c2_mirka',
                'file_name' => '61749cdc2a3c2_mirka.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 86695,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 43,
                'created_at' => '2021-10-23 23:38:06',
                'updated_at' => '2021-10-23 23:38:06',
            ),
            30 => 
            array (
                'id' => 48,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 12,
                'uuid' => 'b5fb07d5-a310-4f6c-96a4-2d9ae41a016d',
                'collection_name' => 'logo',
                'name' => '61749d67cbc08_x-kote-logo',
                'file_name' => '61749d67cbc08_x-kote-logo.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 17666,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 45,
                'created_at' => '2021-10-23 23:40:26',
                'updated_at' => '2021-10-23 23:40:26',
            ),
            31 => 
            array (
                'id' => 50,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 13,
                'uuid' => 'c5138a3b-3d0d-495d-9e54-62ae05c53473',
                'collection_name' => 'logo',
                'name' => '61749dae8ebce_LAVOR',
                'file_name' => '61749dae8ebce_LAVOR.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 60004,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 47,
                'created_at' => '2021-10-23 23:41:42',
                'updated_at' => '2021-10-23 23:41:43',
            ),
            32 => 
            array (
                'id' => 52,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 14,
                'uuid' => '770c6cee-c998-4288-8563-52606b974b77',
                'collection_name' => 'logo',
                'name' => '61749dfde7378_service-car-detail2',
                'file_name' => '61749dfde7378_service-car-detail2.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 110963,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 49,
                'created_at' => '2021-10-23 23:42:55',
                'updated_at' => '2021-10-23 23:42:56',
            ),
            33 => 
            array (
                'id' => 54,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 15,
                'uuid' => 'd23a1494-ea30-4de6-913d-30f8f44f7ef0',
                'collection_name' => 'logo',
                'name' => '61749e4949359_LOGO DETAIL MAGNO CLEAN',
                'file_name' => '61749e4949359_LOGO-DETAIL-MAGNO-CLEAN.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 49831,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 51,
                'created_at' => '2021-10-23 23:44:11',
                'updated_at' => '2021-10-23 23:44:11',
            ),
            34 => 
            array (
                'id' => 56,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 16,
                'uuid' => '5e2f3094-f78b-4a36-bb99-0f1c72b30edd',
                'collection_name' => 'logo',
                'name' => '61749e9d20ac0_LOGO VAPORZA',
                'file_name' => '61749e9d20ac0_LOGO-VAPORZA.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 596336,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 53,
                'created_at' => '2021-10-23 23:45:45',
                'updated_at' => '2021-10-23 23:45:46',
            ),
            35 => 
            array (
                'id' => 58,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 17,
                'uuid' => '11b0a54f-37ca-4b84-833b-4d7c2667ebf3',
                'collection_name' => 'logo',
                'name' => '61749f036d80c_gyeon',
                'file_name' => '61749f036d80c_gyeon.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 60780,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 55,
                'created_at' => '2021-10-23 23:47:17',
                'updated_at' => '2021-10-23 23:47:17',
            ),
            36 => 
            array (
                'id' => 60,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 18,
                'uuid' => '38c73586-f53e-4b43-82e0-2ca267b09724',
                'collection_name' => 'logo',
                'name' => '61749f72e2717_auto finish professional',
                'file_name' => '61749f72e2717_auto-finish-professional.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 61827,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 57,
                'created_at' => '2021-10-23 23:49:09',
                'updated_at' => '2021-10-23 23:49:10',
            ),
            37 => 
            array (
                'id' => 62,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 19,
                'uuid' => '2940803f-6068-4d0f-884a-1b4f227c6bc9',
                'collection_name' => 'logo',
                'name' => '61749fedae701_bodyshop',
                'file_name' => '61749fedae701_bodyshop.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 654768,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 59,
                'created_at' => '2021-10-23 23:51:17',
                'updated_at' => '2021-10-23 23:51:18',
            ),
            38 => 
            array (
                'id' => 64,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 20,
                'uuid' => '00387c07-68fe-421a-b36f-4aaf1e619daf',
                'collection_name' => 'logo',
                'name' => '6174a06a93467_sheiks detail ',
                'file_name' => '6174a06a93467_sheiks-detail-.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 396961,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 61,
                'created_at' => '2021-10-23 23:53:24',
                'updated_at' => '2021-10-23 23:53:26',
            ),
            39 => 
            array (
                'id' => 66,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 21,
                'uuid' => 'c3746d2b-6746-4e68-974a-579013a1a388',
                'collection_name' => 'logo',
                'name' => '6174a0d118ad8_perfect-shine',
                'file_name' => '6174a0d118ad8_perfect-shine.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 53849,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 63,
                'created_at' => '2021-10-23 23:54:58',
                'updated_at' => '2021-10-23 23:54:59',
            ),
            40 => 
            array (
                'id' => 68,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 22,
                'uuid' => '4e4371e5-9c5d-410d-9761-c16e026a3660',
                'collection_name' => 'logo',
                'name' => '6174a1230467e_DDEPOT_2',
                'file_name' => '6174a1230467e_DDEPOT_2.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 23337,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 65,
                'created_at' => '2021-10-23 23:56:20',
                'updated_at' => '2021-10-23 23:56:21',
            ),
            41 => 
            array (
                'id' => 70,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 23,
                'uuid' => '0e19fc41-3f88-47ec-942e-1b8c172f546c',
                'collection_name' => 'logo',
                'name' => '6174a24287524_llantas',
                'file_name' => '6174a24287524_llantas.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 180988,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 67,
                'created_at' => '2021-10-24 00:01:12',
                'updated_at' => '2021-10-24 00:01:13',
            ),
            42 => 
            array (
                'id' => 72,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 24,
                'uuid' => '66236af7-4b0a-4273-aefb-6ae7ff89a345',
                'collection_name' => 'logo',
                'name' => '6174a29197b98_cienfuegos',
                'file_name' => '6174a29197b98_cienfuegos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 633196,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 69,
                'created_at' => '2021-10-24 00:02:28',
                'updated_at' => '2021-10-24 00:02:29',
            ),
            43 => 
            array (
                'id' => 74,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 25,
                'uuid' => '8d993acf-f76a-4f0a-aab6-6b726faa9cf5',
                'collection_name' => 'logo',
                'name' => '6174a2dea7c21_margrey',
                'file_name' => '6174a2dea7c21_margrey.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 49511,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 71,
                'created_at' => '2021-10-24 00:03:49',
                'updated_at' => '2021-10-24 00:03:50',
            ),
            44 => 
            array (
                'id' => 76,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 26,
                'uuid' => '30d3bff4-9a0c-4a8e-8a03-5bb5ceb84409',
                'collection_name' => 'logo',
                'name' => '6174a32a0d659_brillamex2',
                'file_name' => '6174a32a0d659_brillamex2.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 5664,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 73,
                'created_at' => '2021-10-24 00:05:07',
                'updated_at' => '2021-10-24 00:05:07',
            ),
            45 => 
            array (
                'id' => 78,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 27,
                'uuid' => 'c2c7717b-7a5d-4cd3-a436-58a233b09827',
                'collection_name' => 'logo',
                'name' => '6174b53318283_bandrop',
                'file_name' => '6174b53318283_bandrop.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 324340,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 75,
                'created_at' => '2021-10-24 01:22:01',
                'updated_at' => '2021-10-24 01:22:02',
            ),
            46 => 
            array (
                'id' => 80,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 28,
                'uuid' => '41d528c5-ac82-460e-be2b-804222683b3f',
                'collection_name' => 'logo',
                'name' => '6174b5a8601b9_supreme-shine-premier',
                'file_name' => '6174b5a8601b9_supreme-shine-premier.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 61471,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 77,
                'created_at' => '2021-10-24 01:23:54',
                'updated_at' => '2021-10-24 01:23:54',
            ),
            47 => 
            array (
                'id' => 82,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 29,
                'uuid' => '5e1c6b91-7df3-4ae9-bdb9-046e08d0dab2',
                'collection_name' => 'logo',
                'name' => '6174b5fd4aa65_logo_carblock_bco',
                'file_name' => '6174b5fd4aa65_logo_carblock_bco.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 52713,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 79,
                'created_at' => '2021-10-24 01:25:22',
                'updated_at' => '2021-10-24 01:25:22',
            ),
            48 => 
            array (
                'id' => 84,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 30,
                'uuid' => '9d76d35a-92cc-4109-af7e-1d6736d1590f',
                'collection_name' => 'logo',
                'name' => '6174b64e73f62_wash-monkey',
                'file_name' => '6174b64e73f62_wash-monkey.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 46086,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 81,
                'created_at' => '2021-10-24 01:26:40',
                'updated_at' => '2021-10-24 01:26:41',
            ),
            49 => 
            array (
                'id' => 86,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 31,
                'uuid' => 'c07eb877-c8dd-4b76-93b6-fa6afa17e8f9',
                'collection_name' => 'logo',
                'name' => '6174b6da3fbf4_llantas',
                'file_name' => '6174b6da3fbf4_llantas.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 180988,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 83,
                'created_at' => '2021-10-24 01:29:04',
                'updated_at' => '2021-10-24 01:29:05',
            ),
            50 => 
            array (
                'id' => 88,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 32,
                'uuid' => 'b54e2355-ac55-4638-b953-3b2f992d4917',
                'collection_name' => 'logo',
                'name' => '6174b83938e62_LOGO BDS HD WEB',
                'file_name' => '6174b83938e62_LOGO-BDS-HD-WEB.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 224207,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 85,
                'created_at' => '2021-10-24 01:34:51',
                'updated_at' => '2021-10-24 01:34:52',
            ),
            51 => 
            array (
                'id' => 90,
                'model_type' => 'App\\Models\\Exponent',
                'model_id' => 1,
                'uuid' => 'd7833c8f-816e-463f-a332-e42b2412f850',
                'collection_name' => 'photo',
                'name' => '6174b958823ad_Juan Vidrio Redonda',
                'file_name' => '6174b958823ad_Juan-Vidrio-Redonda.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 211037,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 87,
                'created_at' => '2021-10-24 01:44:36',
                'updated_at' => '2021-10-24 01:44:37',
            ),
            52 => 
            array (
                'id' => 92,
                'model_type' => 'App\\Models\\Exponent',
                'model_id' => 2,
                'uuid' => 'ac15775e-770f-45ee-8a85-7b060a7d9701',
                'collection_name' => 'photo',
                'name' => '6176e2590519e_emir',
                'file_name' => '6176e2590519e_emir.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 190070,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 88,
                'created_at' => '2021-10-25 16:59:06',
                'updated_at' => '2021-10-25 16:59:07',
            ),
            53 => 
            array (
                'id' => 93,
                'model_type' => 'App\\Models\\Exponent',
                'model_id' => 3,
                'uuid' => '62e36564-4189-43d9-98bb-5bf317cdda77',
                'collection_name' => 'photo',
                'name' => '6176ec2284483_carmen',
                'file_name' => '6176ec2284483_carmen.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 183073,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 89,
                'created_at' => '2021-10-25 17:40:52',
                'updated_at' => '2021-10-25 17:40:53',
            ),
            54 => 
            array (
                'id' => 94,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 32,
                'uuid' => 'ebbcae82-2e62-456f-b5ed-deedfb5992ba',
                'collection_name' => 'image',
                'name' => '6177035ea2153_fondos',
                'file_name' => '6177035ea2153_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 90,
                'created_at' => '2021-10-25 19:20:00',
                'updated_at' => '2021-10-25 19:20:00',
            ),
            55 => 
            array (
                'id' => 95,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 31,
                'uuid' => 'a7fff93f-d179-48e4-8f01-fa7f927fe6ac',
                'collection_name' => 'image',
                'name' => '617703d3d867a_fondos',
                'file_name' => '617703d3d867a_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 91,
                'created_at' => '2021-10-25 19:21:56',
                'updated_at' => '2021-10-25 19:21:57',
            ),
            56 => 
            array (
                'id' => 96,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 30,
                'uuid' => '04790514-8bfd-4e68-82d3-c98efbc18d11',
                'collection_name' => 'image',
                'name' => '617703e68e78a_fondos',
                'file_name' => '617703e68e78a_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 92,
                'created_at' => '2021-10-25 19:22:15',
                'updated_at' => '2021-10-25 19:22:15',
            ),
            57 => 
            array (
                'id' => 97,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 29,
                'uuid' => 'c606c1fe-0866-45ba-904c-0b443033fdc1',
                'collection_name' => 'image',
                'name' => '617703fd9b2e1_fondos',
                'file_name' => '617703fd9b2e1_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 93,
                'created_at' => '2021-10-25 19:22:38',
                'updated_at' => '2021-10-25 19:22:38',
            ),
            58 => 
            array (
                'id' => 98,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 28,
                'uuid' => 'd0ab0dc0-e72b-477a-a405-cdd0f50571a3',
                'collection_name' => 'image',
                'name' => '6177040b94703_fondos',
                'file_name' => '6177040b94703_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 94,
                'created_at' => '2021-10-25 19:22:52',
                'updated_at' => '2021-10-25 19:22:52',
            ),
            59 => 
            array (
                'id' => 99,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 27,
                'uuid' => 'c72ca0a0-0b35-441d-a045-724bce25d47f',
                'collection_name' => 'image',
                'name' => '6177041a05a93_fondos',
                'file_name' => '6177041a05a93_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 95,
                'created_at' => '2021-10-25 19:23:06',
                'updated_at' => '2021-10-25 19:23:07',
            ),
            60 => 
            array (
                'id' => 100,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 26,
                'uuid' => '9968f318-5b41-46f5-abd0-d30dbd775213',
                'collection_name' => 'image',
                'name' => '61770427f25fb_fondos',
                'file_name' => '61770427f25fb_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 96,
                'created_at' => '2021-10-25 19:23:20',
                'updated_at' => '2021-10-25 19:23:21',
            ),
            61 => 
            array (
                'id' => 101,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 25,
                'uuid' => '62cfade3-d9ab-45cb-957b-839e04dcadd6',
                'collection_name' => 'image',
                'name' => '61770435a5b38_fondos',
                'file_name' => '61770435a5b38_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 97,
                'created_at' => '2021-10-25 19:23:34',
                'updated_at' => '2021-10-25 19:23:35',
            ),
            62 => 
            array (
                'id' => 102,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 24,
                'uuid' => '5a409984-d0cc-4076-83a1-7f1eff9763cd',
                'collection_name' => 'image',
                'name' => '61770443b430f_fondos',
                'file_name' => '61770443b430f_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 98,
                'created_at' => '2021-10-25 19:23:48',
                'updated_at' => '2021-10-25 19:23:49',
            ),
            63 => 
            array (
                'id' => 103,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 23,
                'uuid' => 'ab9001e7-812c-4d51-9b9a-f7d4ea3bf01a',
                'collection_name' => 'image',
                'name' => '617704555a7bd_fondos',
                'file_name' => '617704555a7bd_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 99,
                'created_at' => '2021-10-25 19:24:07',
                'updated_at' => '2021-10-25 19:24:07',
            ),
            64 => 
            array (
                'id' => 104,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 22,
                'uuid' => '213b52fe-9104-4396-9f6d-3200c0dc7ddc',
                'collection_name' => 'image',
                'name' => '61770463eaa1f_fondos',
                'file_name' => '61770463eaa1f_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 100,
                'created_at' => '2021-10-25 19:24:20',
                'updated_at' => '2021-10-25 19:24:21',
            ),
            65 => 
            array (
                'id' => 105,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 21,
                'uuid' => 'b01d5052-6543-42d8-a4cc-abec62b0e8e0',
                'collection_name' => 'image',
                'name' => '61770476f1e7e_fondos',
                'file_name' => '61770476f1e7e_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 101,
                'created_at' => '2021-10-25 19:24:39',
                'updated_at' => '2021-10-25 19:24:40',
            ),
            66 => 
            array (
                'id' => 106,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 20,
                'uuid' => '1faa8005-2dd4-48f2-98c7-b6c6d42eb5a6',
                'collection_name' => 'image',
                'name' => '6177048600330_fondos',
                'file_name' => '6177048600330_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 102,
                'created_at' => '2021-10-25 19:24:54',
                'updated_at' => '2021-10-25 19:24:55',
            ),
            67 => 
            array (
                'id' => 107,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 19,
                'uuid' => '1a646534-ff88-46f1-b304-49db2fc4e1cc',
                'collection_name' => 'image',
                'name' => '61770494f2882_fondos',
                'file_name' => '61770494f2882_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 103,
                'created_at' => '2021-10-25 19:25:09',
                'updated_at' => '2021-10-25 19:25:10',
            ),
            68 => 
            array (
                'id' => 108,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 18,
                'uuid' => '5238f73d-2bf9-4bb1-ac49-6176e83d6569',
                'collection_name' => 'image',
                'name' => '617704abee348_fondos',
                'file_name' => '617704abee348_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 104,
                'created_at' => '2021-10-25 19:25:32',
                'updated_at' => '2021-10-25 19:25:33',
            ),
            69 => 
            array (
                'id' => 109,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 17,
                'uuid' => '6bfd9fe0-6991-4b29-81ef-1f74d32377fc',
                'collection_name' => 'image',
                'name' => '617704ba0f036_fondos',
                'file_name' => '617704ba0f036_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 105,
                'created_at' => '2021-10-25 19:25:46',
                'updated_at' => '2021-10-25 19:25:47',
            ),
            70 => 
            array (
                'id' => 110,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 16,
                'uuid' => '90e82772-507e-405c-88e2-5f5a0ffc5460',
                'collection_name' => 'image',
                'name' => '617704c839201_fondos',
                'file_name' => '617704c839201_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 106,
                'created_at' => '2021-10-25 19:26:01',
                'updated_at' => '2021-10-25 19:26:01',
            ),
            71 => 
            array (
                'id' => 111,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 15,
                'uuid' => 'b4688e30-b34a-44b0-953d-085ae428fe73',
                'collection_name' => 'image',
                'name' => '617704d7282c7_fondos',
                'file_name' => '617704d7282c7_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 107,
                'created_at' => '2021-10-25 19:26:15',
                'updated_at' => '2021-10-25 19:26:16',
            ),
            72 => 
            array (
                'id' => 112,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 14,
                'uuid' => '35ca51ba-d6a9-4b94-8200-754ac6650ed0',
                'collection_name' => 'image',
                'name' => '617704e69c09a_fondos',
                'file_name' => '617704e69c09a_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 108,
                'created_at' => '2021-10-25 19:26:31',
                'updated_at' => '2021-10-25 19:26:31',
            ),
            73 => 
            array (
                'id' => 113,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 13,
                'uuid' => '4081467d-0766-4996-9867-a6acb9b34688',
                'collection_name' => 'image',
                'name' => '617704f489cb5_fondos',
                'file_name' => '617704f489cb5_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 109,
                'created_at' => '2021-10-25 19:26:45',
                'updated_at' => '2021-10-25 19:26:45',
            ),
            74 => 
            array (
                'id' => 114,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 12,
                'uuid' => 'fefc786d-0cdd-4531-81bb-8cfb8fdafb05',
                'collection_name' => 'image',
                'name' => '61770501126ed_fondos',
                'file_name' => '61770501126ed_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 110,
                'created_at' => '2021-10-25 19:26:57',
                'updated_at' => '2021-10-25 19:26:58',
            ),
            75 => 
            array (
                'id' => 115,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 11,
                'uuid' => 'acca0378-3355-4639-bdc5-685e4055fb84',
                'collection_name' => 'image',
                'name' => '6177050f2232f_fondos',
                'file_name' => '6177050f2232f_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 111,
                'created_at' => '2021-10-25 19:27:11',
                'updated_at' => '2021-10-25 19:27:12',
            ),
            76 => 
            array (
                'id' => 116,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 10,
                'uuid' => '5e896fff-69bd-4aa4-8d12-6166ef3dfa41',
                'collection_name' => 'image',
                'name' => '6177051c8a6bb_fondos',
                'file_name' => '6177051c8a6bb_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 112,
                'created_at' => '2021-10-25 19:27:25',
                'updated_at' => '2021-10-25 19:27:25',
            ),
            77 => 
            array (
                'id' => 117,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 9,
                'uuid' => '69df0482-a6d4-4e75-8c5a-f681c2ea2e95',
                'collection_name' => 'image',
                'name' => '6177052a7a222_fondos',
                'file_name' => '6177052a7a222_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 113,
                'created_at' => '2021-10-25 19:27:38',
                'updated_at' => '2021-10-25 19:27:39',
            ),
            78 => 
            array (
                'id' => 118,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 8,
                'uuid' => '3c88ae78-7d3e-495c-b913-295cb3195b2e',
                'collection_name' => 'image',
                'name' => '61770536aab41_fondos',
                'file_name' => '61770536aab41_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 114,
                'created_at' => '2021-10-25 19:27:51',
                'updated_at' => '2021-10-25 19:27:51',
            ),
            79 => 
            array (
                'id' => 119,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 7,
                'uuid' => '8cb8087d-ef51-4de6-810b-2cdb6e421ba1',
                'collection_name' => 'image',
                'name' => '61770542d000e_fondos',
                'file_name' => '61770542d000e_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 115,
                'created_at' => '2021-10-25 19:28:03',
                'updated_at' => '2021-10-25 19:28:03',
            ),
            80 => 
            array (
                'id' => 120,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 6,
                'uuid' => '6a8cae71-d8ec-41e7-9d66-86ee8bcead33',
                'collection_name' => 'image',
                'name' => '6177054e6ca91_fondos',
                'file_name' => '6177054e6ca91_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 116,
                'created_at' => '2021-10-25 19:28:15',
                'updated_at' => '2021-10-25 19:28:16',
            ),
            81 => 
            array (
                'id' => 121,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 5,
                'uuid' => '6149c744-6b91-4d4f-b3b4-17c013102cc3',
                'collection_name' => 'image',
                'name' => '6177055dbd0c9_fondos',
                'file_name' => '6177055dbd0c9_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 117,
                'created_at' => '2021-10-25 19:28:31',
                'updated_at' => '2021-10-25 19:28:31',
            ),
            82 => 
            array (
                'id' => 122,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 4,
                'uuid' => 'a1e2908a-a39d-4713-b8e7-f554e83dc919',
                'collection_name' => 'image',
                'name' => '6177056d0cc0d_fondos',
                'file_name' => '6177056d0cc0d_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 118,
                'created_at' => '2021-10-25 19:28:45',
                'updated_at' => '2021-10-25 19:28:46',
            ),
            83 => 
            array (
                'id' => 123,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 3,
                'uuid' => 'f4c5c485-b057-4238-a5e0-d594c0f2ddf5',
                'collection_name' => 'image',
                'name' => '6177057cefcfb_fondos',
                'file_name' => '6177057cefcfb_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 119,
                'created_at' => '2021-10-25 19:29:01',
                'updated_at' => '2021-10-25 19:29:02',
            ),
            84 => 
            array (
                'id' => 124,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 2,
                'uuid' => '87fda38d-8d91-49d6-a96e-afb226696b26',
                'collection_name' => 'image',
                'name' => '6177059b1af82_fondos',
                'file_name' => '6177059b1af82_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 120,
                'created_at' => '2021-10-25 19:29:32',
                'updated_at' => '2021-10-25 19:29:32',
            ),
            85 => 
            array (
                'id' => 125,
                'model_type' => 'App\\Models\\Marca',
                'model_id' => 1,
                'uuid' => '0c8364d8-9da3-43c4-a963-aa8622c1dad3',
                'collection_name' => 'image',
                'name' => '617705a7e2ea0_fondos',
                'file_name' => '617705a7e2ea0_fondos.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 79036,
                'manipulations' => '[]',
                'custom_properties' => '{"generated_conversions": {"thumb": true, "preview": true}}',
                'responsive_images' => '[]',
                'order_column' => 121,
                'created_at' => '2021-10-25 19:29:44',
                'updated_at' => '2021-10-25 19:29:45',
            ),
        ));
        
        
    }
}